<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.8.2 on win32)" generated="20231219 13:01:09.413" rpa="false" schemaversion="4">
<suite id="s1" name="Exception Demo" source="C:\Works\PythonWork\RobotFrameworkDemo17122023\exception_demo.robot">
<test id="s1-t1" name="Try/Except-First test Fail" line="5">
<kw name="Log To Console" library="BuiltIn">
<arg>Try/Except-First test</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.440" endtime="20231219 13:01:09.440"/>
</kw>
<try>
<branch type="TRY">
<kw name="Log To Console" library="BuiltIn">
<arg>Try block running</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.440" endtime="20231219 13:01:09.441"/>
</kw>
<kw name="Fail" library="BuiltIn">
<arg>Error occured</arg>
<doc>Fails the test with the given message and optionally alters its tags.</doc>
<msg timestamp="20231219 13:01:09.441" level="FAIL">Error occured</msg>
<status status="FAIL" starttime="20231219 13:01:09.441" endtime="20231219 13:01:09.441"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>after the fail</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20231219 13:01:09.441" endtime="20231219 13:01:09.441"/>
</kw>
<status status="FAIL" starttime="20231219 13:01:09.440" endtime="20231219 13:01:09.441"/>
</branch>
<branch type="EXCEPT">
<kw name="Log To Console" library="BuiltIn">
<arg>it is failed</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.441" endtime="20231219 13:01:09.442"/>
</kw>
<status status="PASS" starttime="20231219 13:01:09.441" endtime="20231219 13:01:09.442"/>
</branch>
<branch type="ELSE">
<kw name="Log To Console" library="BuiltIn">
<arg>Else is executed</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20231219 13:01:09.442" endtime="20231219 13:01:09.442"/>
</kw>
<status status="NOT RUN" starttime="20231219 13:01:09.442" endtime="20231219 13:01:09.442"/>
</branch>
<branch type="FINALLY">
<kw name="Log To Console" library="BuiltIn">
<arg>FINALLY is executed</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.443" endtime="20231219 13:01:09.443"/>
</kw>
<status status="PASS" starttime="20231219 13:01:09.442" endtime="20231219 13:01:09.443"/>
</branch>
<status status="PASS" starttime="20231219 13:01:09.440" endtime="20231219 13:01:09.443"/>
</try>
<status status="PASS" starttime="20231219 13:01:09.439" endtime="20231219 13:01:09.443"/>
</test>
<test id="s1-t2" name="Try/Except-First test Pass" line="19">
<kw name="Log To Console" library="BuiltIn">
<arg>Try/Except-First test</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.445" endtime="20231219 13:01:09.445"/>
</kw>
<try>
<branch type="TRY">
<kw name="Log To Console" library="BuiltIn">
<arg>Try block running</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.446" endtime="20231219 13:01:09.446"/>
</kw>
<kw name="Log To Console" library="BuiltIn">
<arg>after the fail</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.447" endtime="20231219 13:01:09.450"/>
</kw>
<status status="PASS" starttime="20231219 13:01:09.445" endtime="20231219 13:01:09.450"/>
</branch>
<branch type="EXCEPT">
<kw name="Log To Console" library="BuiltIn">
<arg>it is failed</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" starttime="20231219 13:01:09.450" endtime="20231219 13:01:09.450"/>
</kw>
<status status="NOT RUN" starttime="20231219 13:01:09.450" endtime="20231219 13:01:09.450"/>
</branch>
<branch type="ELSE">
<kw name="Log To Console" library="BuiltIn">
<arg>Else is executed</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.451" endtime="20231219 13:01:09.451"/>
</kw>
<status status="PASS" starttime="20231219 13:01:09.451" endtime="20231219 13:01:09.451"/>
</branch>
<branch type="FINALLY">
<kw name="Log To Console" library="BuiltIn">
<arg>FINALLY is executed</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" starttime="20231219 13:01:09.451" endtime="20231219 13:01:09.452"/>
</kw>
<status status="PASS" starttime="20231219 13:01:09.451" endtime="20231219 13:01:09.452"/>
</branch>
<status status="PASS" starttime="20231219 13:01:09.445" endtime="20231219 13:01:09.452"/>
</try>
<status status="PASS" starttime="20231219 13:01:09.444" endtime="20231219 13:01:09.453"/>
</test>
<doc>This is the example of Exception</doc>
<status status="PASS" starttime="20231219 13:01:09.415" endtime="20231219 13:01:09.454"/>
</suite>
<statistics>
<total>
<stat pass="2" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="2" fail="0" skip="0" id="s1" name="Exception Demo">Exception Demo</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
